import 'package:get/get.dart';

class EmojiMenuController extends GetxController {
  static EmojiMenuController get instance => Get.find();
  List<String> emojiWithValue = [
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
     "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
     "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
     "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
     "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
        "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",
    "assets/images/smiling_face_with _halo.png",

  ];
  List<String> Emojis = [
    "assets/images/smiling_emoji.png",
    "assets/images/smiling_emoji.png",
    "assets/images/smiling_emoji.png",
    "assets/images/smiling_emoji.png",
    "assets/images/smiling_emoji.png",
    "assets/images/smiling_emoji.png",
    "assets/images/smiling_emoji.png",
    "assets/images/smiling_emoji.png",
    "assets/images/smiling_emoji.png",
    "assets/images/smiling_emoji.png",
    "assets/images/smiling_emoji.png",
    "assets/images/smiling_emoji.png",
    "assets/images/smiling_emoji.png",
    "assets/images/smiling_emoji.png",
    "assets/images/smiling_emoji.png",
    "assets/images/smiling_emoji.png",
    "assets/images/smiling_emoji.png",
    "assets/images/smiling_emoji.png",
    "assets/images/smiling_emoji.png",
    "assets/images/smiling_emoji.png",
    "assets/images/smiling_emoji.png",
    "assets/images/smiling_emoji.png",
    "assets/images/smiling_emoji.png",
    "assets/images/smiling_emoji.png",
  ];
}
