// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjDPFuatKOtGrz0ClLoMVWrSpBwmPrqyI',
    appId: '1:951030714207:web:285205224aed2efa32f0ea',
    messagingSenderId: '951030714207',
    projectId: 'findme-82dd5',
    authDomain: 'findme-82dd5.firebaseapp.com',
    storageBucket: 'findme-82dd5.appspot.com',
    measurementId: 'G-YDLWBFGBEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM8C31Q--h0sFyU8OCAlqxDbvv3EJsg1s',
    appId: '1:951030714207:android:117214afb26132c232f0ea',
    messagingSenderId: '951030714207',
    projectId: 'findme-82dd5',
    storageBucket: 'findme-82dd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKgaJMyvw_fuYqqkKMQtvqQ7bxbWXh73k',
    appId: '1:951030714207:ios:554a20d8b577702d32f0ea',
    messagingSenderId: '951030714207',
    projectId: 'findme-82dd5',
    storageBucket: 'findme-82dd5.appspot.com',
    iosBundleId: 'com.tritec.findMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKgaJMyvw_fuYqqkKMQtvqQ7bxbWXh73k',
    appId: '1:951030714207:ios:554a20d8b577702d32f0ea',
    messagingSenderId: '951030714207',
    projectId: 'findme-82dd5',
    storageBucket: 'findme-82dd5.appspot.com',
    iosBundleId: 'com.tritec.findMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjDPFuatKOtGrz0ClLoMVWrSpBwmPrqyI',
    appId: '1:951030714207:web:2d8aa7d00b90a33432f0ea',
    messagingSenderId: '951030714207',
    projectId: 'findme-82dd5',
    authDomain: 'findme-82dd5.firebaseapp.com',
    storageBucket: 'findme-82dd5.appspot.com',
    measurementId: 'G-FPG11ZCVQB',
  );

}