// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbAGcrvEvN8g9WklpHmXJrfN3Qn7AXwIk',
    appId: '1:279723335521:web:96b6ae87fe78cff716af20',
    messagingSenderId: '279723335521',
    projectId: 'findme-69e77',
    authDomain: 'findme-69e77.firebaseapp.com',
    storageBucket: 'findme-69e77.appspot.com',
    measurementId: 'G-4K8DSH10G7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl7wgXKbymjz-aW7kM5y3cnmmvPa5cLK0',
    appId: '1:279723335521:android:f8ae6a5fe75c826816af20',
    messagingSenderId: '279723335521',
    projectId: 'findme-69e77',
    storageBucket: 'findme-69e77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9vsV9WL-ekSKmCGC6bFB-QyZKHe8cbCg',
    appId: '1:279723335521:ios:e5480cf0661d2e8b16af20',
    messagingSenderId: '279723335521',
    projectId: 'findme-69e77',
    storageBucket: 'findme-69e77.appspot.com',
    iosBundleId: 'com.tritec.findMee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9vsV9WL-ekSKmCGC6bFB-QyZKHe8cbCg',
    appId: '1:279723335521:ios:6bc31aee059257d816af20',
    messagingSenderId: '279723335521',
    projectId: 'findme-69e77',
    storageBucket: 'findme-69e77.appspot.com',
    iosBundleId: 'com.tritec.findMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbAGcrvEvN8g9WklpHmXJrfN3Qn7AXwIk',
    appId: '1:279723335521:web:4f25eb4c3d56d8a316af20',
    messagingSenderId: '279723335521',
    projectId: 'findme-69e77',
    authDomain: 'findme-69e77.firebaseapp.com',
    storageBucket: 'findme-69e77.appspot.com',
    measurementId: 'G-TCSR26K4BC',
  );

}